06_DJANGO_ADVANCE/01_DJANGO_RECAP/django_recap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('board/', include('board.urls')),
    path('poll/', include('poll.urls')),
]

06_DJANGO_ADVANCE/01_DJANGO_RECAP/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),  # home/
    path('guess/', views.guess, name='guess'),  # home/guess/
    path('answer/', views.answer, name='answer'),  # home/answer
]

06_DJANGO_ADVANCE/01_DJANGO_RECAP/home/views.py
from django.shortcuts import render, HttpResponse


def index(request):
    return render(request, 'home/index.html')


def guess(request):
    return render(request, 'home/guess.html')


def answer(request):
    count = 0
    if request.POST.get('q1') == 'a':
        count += 1
    if request.POST.get('q2') == 'b':
        count += 1
    if request.POST.get('q3') == 'c':
        count += 1

    return render(request, 'home/answer.html', {
        'count': count,
    })

06_DJANGO_ADVANCE/01_DJANGO_RECAP/home/templates/home/answer.html
{% extends 'home/base.html' %}
{% block title %}
    Answer
{% endblock %}

{% block body %}
    <h1>Answer</h1>
    <p>{{ count }} 개 맞았습니다.</p>
{% endblock %}

06_DJANGO_ADVANCE/01_DJANGO_RECAP/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <ul>
        <li><a href="{% url 'home:index' %}">Index</a></li>
        <li><a href="{% url 'home:guess' %}">guess</a></li>
    </ul>
    {% block body %}
    {% endblock %}
</body>
</html>

06_DJANGO_ADVANCE/01_DJANGO_RECAP/home/templates/home/guess.html
{% extends 'home/base.html' %}

{% block title %}
    Guess me
{% endblock %}

{% block body %}
    <h1>질문지</h1>
    <form action="{% url 'home:answer' %}" method="POST">
        {% csrf_token %}
        <div>
            <label for="q1">내 생일은?</label>
            <input id="q1" name="q1" type="text">
        </div>
        <div>
            <label for="q2">내 머리 길이는?</label>
            <input id="q2" name="q2" type="text">
        </div>
        <div>
            <label for="q3">내 무릎 상태는?</label>
            <input id="q3" name="q3" type="text">
        </div>
        <input type="submit">
    </form>
{% endblock %}

06_DJANGO_ADVANCE/01_DJANGO_RECAP/home/templates/home/index.html
{% extends 'base.html' %}

{% block title %}
    INDEX
{% endblock %}

{% block body %}
    <h1>This is index</h1>
{% endblock %}