06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    # Read 글 목록(list) render
    path('articles/', views.article_list, name='article_list'),
    # Read 글 상세(detail) render
    path('articles/<int:article_id>/', views.article_detail, name='article_detail'),

    # Create
    path('articles/new/', views.new_article, name='new_article'),

    # Update 
    path('articles/<int:article_id>/edit/', views.edit_article, name='edit_article'),

    # Delete 글 삭제(delete)
    path('articles/<int:article_id>/delete/', views.delete_article, name='delete_article'),

    # Create Comment
    path('articles/<int:article_id>/comments/new/', views.new_comment, name='new_comment'),

    # Delete Comment
    path('articles/<int:article_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),

    path('API/articles/<int:article_id>/', views.article_detail_API, name="article_detail_API"),
    path('API/articles/', views.article_list_API, name="article_list_API"),
]

06_DJANGO_ADVANCE/01_DJANGO_RECAP/django_recap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('board/', include('board.urls')),
    path('poll/', include('poll.urls')),
]

06_DJANGO_ADVANCE/01_DJANGO_RECAP/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),  # home/
    path('guess/', views.guess, name='guess'),  # home/guess/
    path('answer/', views.answer, name='answer'),  # home/answer
]

06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/models.py
from django.db import models
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def get_absolute_url(self):  # detail page 가 있을 때
        return reverse("board:article_detail", kwargs={"article_id": self.id})
    

class Comment(models.Model):
    content = models.CharField(max_length=200)  # 200 넘어가면 뒤에 절삭
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/forms.py
from django import forms
from .models import Article, Comment

# forms.Form => Data 입력/검증 + HTML 제공 => Model 정보 모름
# forms.ModelForm => Data 입력/검증 + HTML 제공 => Model 정보를 알고있음


class ArticleModelForm(forms.ModelForm):
    title = forms.CharField(min_length=2, max_length=100)
    
    class Meta:
        model = Article
        fields = '__all__'


class CommentModelForm(forms.ModelForm):
    content = forms.CharField(min_length=2, max_length=200)  # 200 을 검증

    class Meta:
        model = Comment
        fields = ('content',)

# Ref
class ArticleForm(forms.Form):
    title = forms.CharField(
        min_length=2, max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'my-title',
                'placeholder': 'Enter title plz',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'my-class',
                'placeholder': 'Content is required',
                'rows': 5,
                'cols': 50,
            }
        )
    )

06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods

from .models import Article, Comment
from .forms import ArticleModelForm, CommentModelForm, ArticleForm

from IPython import embed


# CRUD
@require_http_methods(['GET', 'POST'])
def new_article(request):
    if request.method == 'POST':
        form = ArticleModelForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect(article)  # redirect('board:article_detail', article.id)
    else:
        form = ArticleModelForm()
    
    return render(request, 'board/form.html', {
        'form': form,
        'what': 'New'
    })


@require_GET
def article_list(request):
    articles = Article.objects.all()
    return render(request, 'board/list.html', {
        'articles': articles,
    })


@require_GET
def article_detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    comments = article.comment_set.all().order_by('-id')  # Comment.objects.filter(article_id=article.id)
    comment_form = CommentModelForm()

    return render(request, 'board/detail.html', {
        'article': article,
        'comments': comments,
        'comment_form': comment_form,
    })


@require_http_methods(['GET', 'POST'])
def edit_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)

    if request.method == 'POST':
        form = ArticleModelForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect(article)
    else:
        form = ArticleModelForm(instance=article)
    return render(request, 'board/form.html', {
        'form': form,
        'what': 'Edit'
    })
        

@require_POST
def delete_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    article.delete()
    return redirect('board:article_list')


@require_POST
def new_comment(request, article_id):  # /board/articles/N/comments/new/ 
    article = get_object_or_404(Article, id=article_id)
    form = CommentModelForm(request.POST)
    # embed()
    if form.is_valid():
        # comment = Comment()
        # comment.content = request.POST.get('content')
        comment = form.save(commit=False)
        comment.article_id = article.id
        comment.save()
    return redirect(article)


@require_POST
def delete_comment(request, article_id, comment_id):
    from time import time
    comment = get_object_or_404(Comment, id=comment_id, article_id=article_id)
    comment.delete()
    return redirect(comment.article)

"""
@require_http_methods(['GET', 'POST'])
def new(request):
    # 요청이 GET/POST 인지 확인한다.
    # 만약 POST 라면
    if request.method == 'POST':
        # ArticleModelForm 의 인스턴스를 생성하고 Data 를 채운다(binding).
        form = ArticleModelForm(request.POST)
        # binding 된 form 이 유효한지 체크한다.
        if form.is_valid():
            # 유효하다면 form 을 저장한다.
            article = form.save()
            # 저장한 article detail 로 redirect 한다.
            return redirect(article)
        # form 이 유효하지 않다면,
        else:
            # 유효하지 않은 입력데이터를 담은 HTML과 에러메세지를 사용자한테 보여준다.
            return render(request, 'board/new.html', {
                'form': form,
            })
    # GET 이라면
    else:
        # 비어있는 form(HTML 생성기) 을 만든다.
        form = ArticleModelForm()
        # form 과 html 을 사용자에게 보여준다.
        return render(request, 'board/new.html', {
            'form': form,
        })


Create Article with Form
def new_article_with_form(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        embed()
        if form.is_valid():
            article = Article()
            # article.title = request.POST.get('title')  # 검증되지 않은 데이터
            article.title = form.cleaned_data.get('title')  # 검증된 데이터
            article.content = form.cleaned_data.get('content')
            article.save()
            return redirect(article)
    else:
        form = ArticleForm()
    return render(request, 'board/new.html', {
        'form': form,
    })
"""
from django.http import HttpResponse
import json

@require_GET
def article_detail_API(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    data = {
        'id': article.id,
        'title': article.title,
        'content': article.content,
    }

    return HttpResponse(json.dumps(data))

@require_GET
def article_list_API(request):
    articles = Article.objects.all()
    data_set = []
    for article in articles:
        data_set.append({
        'id': article.id,
        'title': article.title,
        'content': article.content,
    })
    return HttpResponse(json.dumps(data_set))

06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/templates/board/_comment.html
<form action="{% url 'board:new_comment' article.id %}" method="POST">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit">
</form>

{% if comments %}
    <ul>
        {% for comment in comments %}
            <li>
                {{ comment.content }}
                <form method="POST" action="{% url 'board:delete_comment' article.id comment.id %}">
                    {% csrf_token %}
                    <input type="submit" value="삭제">
                </form>
                <button>수정</button>
            </li>
        {% endfor %}
    </ul>
{% endif %}

06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/templates/board/_form.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>

06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/templates/board/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block body %}
    {% endblock body %}
</body>
</html>

06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/templates/board/detail.html
{% extends 'base.html' %}
{% block title %}Article detail{% endblock %}

{% block body %}
    <h1>{{ article.title }}</h1>
    <div>
        <small>created: {{ article.created_at }} | </small>
        <small>updated: {{ article.updated_at }}</small>
    </div>
    <p>
        {{ article.content }}
    </p>
    <div>
        <a href="{% url 'board:edit_article' article.id %}">
            <button>수정</button>    
        </a>
    </div>
    <div>
        <form action="{% url 'board:delete_article' article.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제">
        </form>
    </div>
    <hr>
    {% include 'board/_comment.html' %}
{% endblock %}

06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/templates/board/edit.html
{% extends 'base.html' %}
{% block title %}Edit article{% endblock %}

{% block body %}
<h1>Edit article</h1>
{% include 'board/_form.html' %}
{% endblock %}

06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/templates/board/form.html
{% extends 'base.html' %}
{% block title %}{{ what }} article{% endblock %}

{% block body %}
<h1>{{ what }} article</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock %}

06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/templates/board/list.html
{% extends 'base.html' %}
{% block title %}Article list{% endblock %}

{% block body %}
<h1>This is Article list</h1>
<a href="{% url 'board:new_article' %}">New article</a>

{% if articles %}
  <ul>
    {% for article in articles %}
      <li>
        <a href="{{ article.get_absolute_url }}">
          {{ article.title }}
        </a>
      </li>
    {% endfor %}
  </ul>
{% endif %}

{% endblock %}

06_DJANGO_ADVANCE/01_DJANGO_RECAP/board/templates/board/new.html
{% extends 'base.html' %}
{% block title %}New article{% endblock %}

{% block body %}
<h1>New article</h1>
{% include 'board/_form.html' %}
{% endblock %}